# Generated by Django 4.2.3 on 2023-10-08 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("EMediCenter", "0006_alter_gp_availability"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="avatar",
            field=models.ImageField(blank=True, null=True, upload_to="avatars/"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("Male", "M"), ("Female", "F"), ("Other", "O")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.DeleteModel(name="Case",),
    ]
