# Generated by Django 4.2.3 on 2023-10-12 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("EMediCenter", "0007_userprofile_avatar_alter_userprofile_gender_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="avatar",
            field=models.ImageField(default="default.jpg", upload_to="avatars/"),
        ),
    ]
