# Generated by Django 4.2.3 on 2023-10-23 04:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("EMediCenter", "0011_alter_gp_gpid"),
    ]

    operations = [
        migrations.RemoveField(model_name="caregiverorder", name="Date",),
        migrations.AddField(
            model_name="caregiverorder",
            name="end_time",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="caregiverorder",
            name="start_time",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="caregiverorder",
            name="CaregiverID",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="EMediCenter.caregiver"
            ),
        ),
        migrations.AlterField(
            model_name="caregiverorder",
            name="UserID",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
