# Generated by Django 4.2.3 on 2023-10-23 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "EMediCenter",
            "0012_remove_caregiverorder_date_caregiverorder_end_time_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
