# Generated by Django 4.2.3 on 2023-10-24 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("EMediCenter", "0014_alter_caregiverorder_caregiverorderid"),
    ]

    operations = [
        migrations.AddField(
            model_name="caregiver",
            name="Cost",
            field=models.PositiveSmallIntegerField(default=10),
            preserve_default=False,
        ),
    ]
