# Generated by Django 4.2.3 on 2023-10-24 22:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("EMediCenter", "0015_caregiver_cost"),
    ]

    operations = [
        migrations.AlterField(
            model_name="caregiverorder",
            name="UserID",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
