# Generated by Django 4.2.3 on 2023-10-26 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("EMediCenter", "0017_gp_cost_gp_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="caregiver",
            name="Age",
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="caregiver",
            name="Availability",
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="caregiver",
            name="Experience",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="caregiver",
            name="Gender",
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name="caregiver",
            name="Name",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="avatar",
            field=models.ImageField(default="admin1.png", upload_to="avatars/"),
        ),
    ]
