# Generated by Django 4.2.3 on 2023-10-26 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("EMediCenter", "0019_alter_caregiver_cost"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gp",
            name="Age",
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="gp",
            name="Availability",
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="gp",
            name="Experience",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="gp",
            name="Qualification",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
