# Generated by Django 4.2.3 on 2023-11-01 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("EMediCenter", "0020_alter_gp_age_alter_gp_availability_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gporder",
            name="GPOrderID",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
