# Generated by Django 4.2.3 on 2023-11-01 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("EMediCenter", "0021_alter_gporder_gporderid"),
    ]

    operations = [
        migrations.AddField(
            model_name="gporder",
            name="end_time",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="gporder",
            name="start_time",
            field=models.DateTimeField(null=True),
        ),
    ]
