# Generated by Django 4.2.3 on 2023-11-01 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("EMediCenter", "0023_remove_gporder_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="gporder", name="Date", field=models.DateField(null=True),
        ),
    ]
