# Generated by Django 4.2.3 on 2023-10-07 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Caregiver",
            fields=[
                (
                    "CaregiverID",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("Name", models.CharField(max_length=50)),
                ("Gender", models.CharField(max_length=5)),
                ("Age", models.PositiveSmallIntegerField()),
                ("Qualification", models.CharField(max_length=100)),
                ("Experience", models.PositiveIntegerField()),
                ("ServiceArea", models.CharField(max_length=10)),
                ("Availability", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="GP",
            fields=[
                ("GPID", models.BigIntegerField(primary_key=True, serialize=False)),
                ("Name", models.CharField(max_length=50)),
                ("Gender", models.CharField(max_length=5)),
                ("Age", models.PositiveSmallIntegerField()),
                ("Qualification", models.CharField(max_length=100)),
                ("Experience", models.PositiveIntegerField()),
                ("ServiceArea", models.CharField(max_length=10)),
                ("Availability", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "UserID",
                    models.PositiveIntegerField(primary_key=True, serialize=False),
                ),
                ("Username", models.CharField(max_length=20)),
                ("Password", models.CharField(max_length=20)),
                ("PhoneNumber", models.CharField(max_length=20)),
                ("Email", models.EmailField(max_length=20)),
                ("Is_Admin", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "UserID",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="EMediCenter.user",
                    ),
                ),
                ("Gender", models.CharField(max_length=5)),
                ("Height", models.PositiveSmallIntegerField()),
                ("Weight", models.PositiveSmallIntegerField()),
                ("Age", models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="GPOrder",
            fields=[
                (
                    "GPOrderID",
                    models.PositiveIntegerField(primary_key=True, serialize=False),
                ),
                ("Date", models.DateField()),
                ("Cost", models.PositiveSmallIntegerField()),
                (
                    "GPID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="EMediCenter.gp"
                    ),
                ),
                (
                    "UserID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="EMediCenter.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Case",
            fields=[
                (
                    "CaseID",
                    models.PositiveIntegerField(primary_key=True, serialize=False),
                ),
                ("Title", models.CharField(max_length=20, unique=True)),
                ("UserID", models.PositiveIntegerField()),
                ("Description", models.CharField(max_length=100)),
                ("Date", models.DateField()),
                (
                    "GPID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="EMediCenter.gp"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CaregiverOrder",
            fields=[
                (
                    "CaregiverOrderID",
                    models.PositiveIntegerField(primary_key=True, serialize=False),
                ),
                ("Date", models.DateField()),
                ("CaregiverID", models.PositiveIntegerField()),
                ("Cost", models.PositiveSmallIntegerField()),
                (
                    "UserID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="EMediCenter.user",
                    ),
                ),
            ],
        ),
    ]
