# Generated by Django 4.2.3 on 2023-10-07 10:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("EMediCenter", "0002_userprofile_alter_caregiverorder_userid_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PatientCase",
            fields=[
                ("case_id", models.AutoField(primary_key=True, serialize=False)),
                ("disease_name", models.CharField(max_length=100)),
                ("symptoms", models.TextField()),
                ("description", models.TextField()),
                ("prescription", models.TextField()),
                ("diagnosis_date", models.DateField()),
                (
                    "diagnosing_doctor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="diagnosed_cases",
                        to="EMediCenter.gp",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
