# Generated by Django 4.2.3 on 2023-10-07 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("EMediCenter", "0004_userprofile_gender_userprofile_height_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="caregiver",
            name="Availability",
            field=models.CharField(max_length=30),
        ),
    ]
