# Generated by Django 4.2.3 on 2023-10-20 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("EMediCenter", "0008_alter_userprofile_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="caregiver",
            name="avatar",
            field=models.ImageField(default="default1.jpg", upload_to="avatars/"),
        ),
    ]
