# Generated by Django 4.2.3 on 2023-10-20 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("EMediCenter", "0009_caregiver_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="caregiver",
            name="CaregiverID",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
