# Generated by Django 4.2.3 on 2023-10-20 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("EMediCenter", "0010_alter_caregiver_caregiverid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gp",
            name="GPID",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
