# Generated by Django 4.2.3 on 2023-10-24 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("EMediCenter", "0013_userprofile_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="caregiverorder",
            name="CaregiverOrderID",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
