# Generated by Django 4.2.3 on 2023-10-25 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("EMediCenter", "0016_alter_caregiverorder_userid"),
    ]

    operations = [
        migrations.AddField(
            model_name="gp",
            name="Cost",
            field=models.PositiveSmallIntegerField(default=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="gp",
            name="avatar",
            field=models.ImageField(default="default1.jpg", upload_to="avatars/"),
        ),
    ]
