# Generated by Django 4.2.3 on 2023-10-26 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "EMediCenter",
            "0018_alter_caregiver_age_alter_caregiver_availability_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="caregiver",
            name="Cost",
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
