# Generated by Django 4.2.3 on 2023-11-01 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("EMediCenter", "0022_gporder_end_time_gporder_start_time"),
    ]

    operations = [
        migrations.RemoveField(model_name="gporder", name="Date",),
    ]
